# Generated by Django 4.2.2 on 2023-06-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KrDictQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128)),
                ('difficulty', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NaverQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('explain', models.TextField()),
                ('rate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NaverQuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('is_answer', models.BooleanField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='crawled_data.naverquiz')),
            ],
        ),
        migrations.CreateModel(
            name='KrDictQuizExplain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('dict_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explains', to='crawled_data.krdictquiz')),
            ],
        ),
        migrations.CreateModel(
            name='KrDictQuizExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_type', models.PositiveIntegerField()),
                ('content', models.CharField(max_length=256)),
                ('dict_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='crawled_data.krdictquiz')),
            ],
        ),
    ]
