# Generated by Django 4.2.2 on 2023-06-23 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentBattleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btl_title', models.CharField(max_length=60, unique=True)),
                ('btl_category', models.CharField(choices=[('A', '종합'), ('C', '십자말풀이'), ('D', '단어맞추기')], max_length=5)),
                ('btl_created_at', models.DateTimeField(auto_now_add=True)),
                ('btl_updated_at', models.DateTimeField(auto_now=True)),
                ('max_users', models.IntegerField(default=2)),
                ('is_private', models.BooleanField(default=False)),
                ('room_password', models.IntegerField(null=True)),
                ('host_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='host_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('btl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_room_id', to='battle.currentbattlelist')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BattleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
